// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/smsqueue/proto/sms.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Extra                string   `protobuf:"bytes,5,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9617b3e0dd131f16, []int{0}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SendRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SendRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SendRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SendRequest) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type SendResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RawContent           string   `protobuf:"bytes,3,opt,name=rawContent,proto3" json:"rawContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9617b3e0dd131f16, []int{1}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SendResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SendResponse) GetRawContent() string {
	if m != nil {
		return m.RawContent
	}
	return ""
}

func init() {
	proto.RegisterType((*SendRequest)(nil), "SendRequest")
	proto.RegisterType((*SendResponse)(nil), "SendResponse")
}

func init() {
	proto.RegisterFile("services/smsqueue/proto/sms.proto", fileDescriptor_9617b3e0dd131f16)
}

var fileDescriptor_9617b3e0dd131f16 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbf, 0x4e, 0x03, 0x31,
	0x0c, 0x87, 0x75, 0xc0, 0x15, 0x30, 0x65, 0x20, 0x42, 0x10, 0x3a, 0x20, 0xe8, 0x84, 0x18, 0xae,
	0x12, 0x3c, 0x00, 0x12, 0xcc, 0x48, 0xe8, 0x10, 0x0b, 0x13, 0x21, 0xb5, 0x68, 0x87, 0x8b, 0xaf,
	0xb1, 0x43, 0x79, 0x05, 0xde, 0x1a, 0xe5, 0x4f, 0xd1, 0x2d, 0x9d, 0x92, 0xcf, 0x76, 0x9c, 0x4f,
	0x3f, 0xb8, 0x66, 0xf4, 0xdf, 0x4b, 0x8b, 0x3c, 0xe3, 0x8e, 0x57, 0x01, 0x03, 0xce, 0x7a, 0x4f,
	0x42, 0x11, 0x9b, 0x74, 0x9b, 0xfe, 0x56, 0x70, 0xf4, 0x8a, 0x6e, 0xde, 0xe2, 0x2a, 0x20, 0x8b,
	0xd2, 0xb0, 0x6f, 0xac, 0xa5, 0xe0, 0x44, 0x57, 0x57, 0xd5, 0xcd, 0x61, 0xbb, 0x41, 0x35, 0x81,
	0x83, 0xde, 0x30, 0xaf, 0xc9, 0xcf, 0xf5, 0x4e, 0x6a, 0xfd, 0xb3, 0x3a, 0x85, 0xba, 0x5f, 0x90,
	0x43, 0xbd, 0x9b, 0x1a, 0x19, 0xe2, 0x2e, 0x4b, 0x4e, 0xd0, 0x89, 0xde, 0xcb, 0xbb, 0x0a, 0xc6,
	0x79, 0xfc, 0x11, 0x6f, 0x74, 0x9d, 0xe7, 0x13, 0x4c, 0x3f, 0x60, 0x9c, 0x55, 0xb8, 0x27, 0xc7,
	0xa8, 0xce, 0x60, 0xc4, 0x62, 0x24, 0x70, 0x52, 0xa9, 0xdb, 0x42, 0x71, 0x6f, 0x87, 0xcc, 0xe6,
	0x0b, 0x8b, 0xc8, 0x06, 0xd5, 0x25, 0x80, 0x37, 0xeb, 0xa7, 0xf2, 0x69, 0x96, 0x19, 0x54, 0xee,
	0x1e, 0xe0, 0xe4, 0xcd, 0x2d, 0x2d, 0x75, 0xcf, 0xf9, 0xc1, 0x4b, 0xe0, 0x85, 0xba, 0xcd, 0x09,
	0x94, 0x92, 0x1a, 0x37, 0x83, 0x3c, 0x26, 0xc7, 0xcd, 0x50, 0xe9, 0xf1, 0xe2, 0xfd, 0x7c, 0x4b,
	0xa6, 0x9f, 0xa3, 0x74, 0xdc, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x29, 0xd3, 0xcb, 0x98, 0x75,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UnicomMessagePushClient is the client API for UnicomMessagePush service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnicomMessagePushClient interface {
	SendMessage(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

type unicomMessagePushClient struct {
	cc grpc.ClientConnInterface
}

func NewUnicomMessagePushClient(cc grpc.ClientConnInterface) UnicomMessagePushClient {
	return &unicomMessagePushClient{cc}
}

func (c *unicomMessagePushClient) SendMessage(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/UnicomMessagePush/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnicomMessagePushServer is the server API for UnicomMessagePush service.
type UnicomMessagePushServer interface {
	SendMessage(context.Context, *SendRequest) (*SendResponse, error)
}

// UnimplementedUnicomMessagePushServer can be embedded to have forward compatible implementations.
type UnimplementedUnicomMessagePushServer struct {
}

func (*UnimplementedUnicomMessagePushServer) SendMessage(ctx context.Context, req *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}

func RegisterUnicomMessagePushServer(s *grpc.Server, srv UnicomMessagePushServer) {
	s.RegisterService(&_UnicomMessagePush_serviceDesc, srv)
}

func _UnicomMessagePush_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnicomMessagePushServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UnicomMessagePush/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnicomMessagePushServer).SendMessage(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UnicomMessagePush_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UnicomMessagePush",
	HandlerType: (*UnicomMessagePushServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _UnicomMessagePush_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/smsqueue/proto/sms.proto",
}
