// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://hafrans.com",
        "contact": {
            "name": "Chuuka Ro (Hafrans)",
            "url": "http://hafrans.com/support",
            "email": "lvzh@hafrans.com"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/captcha/:id": {
            "get": {
                "description": "获取验证码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "captcha"
                ],
                "summary": "获得验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "验证码id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "同时返回验证码的时间戳、base64化图片、验证码challenge指令",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/auth/employer/register": {
            "post": {
                "description": "用人单位账户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user",
                    "register"
                ],
                "summary": "用人单位 账户注册",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.UserRegisterEmployerForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "422": {
                        "description": "表单绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "500": {
                        "description": "表单绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/auth/labor/register": {
            "post": {
                "description": "劳动者账户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user",
                    "register"
                ],
                "summary": "劳动者 账户注册",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.UserRegisterLaborForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "422": {
                        "description": "表单绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "500": {
                        "description": "表单绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "用户登录并获得token以及失效日期",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "手机号",
                        "name": "phone",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "密码",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "验证码",
                        "name": "captcha_code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "验证码时间戳 （2006-01-02 15:04:05）",
                        "name": "captcha_time",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "验证码挑战指令",
                        "name": "captcha_challenge",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.LoginResult"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/": {
            "get": {
                "description": "上传资源 ，支持 pdf,doc,docx,pdfx,txt,mp3,zip,jpg,gif,jpeg,png格式",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "utils"
                ],
                "summary": "上传资源",
                "parameters": [
                    {
                        "type": "string",
                        "description": "要上传的资源",
                        "name": "file",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/case/": {
            "get": {
                "description": "获取所有的案件，非管理员只能看到自己的，管理员能看到全部人的",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "labor"
                ],
                "summary": "获取所有的案件",
                "parameters": [
                    {
                        "type": "number",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "页大小",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "案件号（case id）模糊查询",
                        "name": "search",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/case/caseId/:caseId": {
            "get": {
                "description": "获取单一Case，通过CaseID 例子：3711002020063019254015935163407436142",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "case"
                ],
                "summary": "通过Case ID（调解申请号）获取case",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "没有认证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/case/create": {
            "post": {
                "description": "由申请人填写创建新调解案件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "case"
                ],
                "summary": "创建新调解案件",
                "parameters": [
                    {
                        "description": "提交表单",
                        "name": "case",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.CaseFirstSubmitForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "没有认证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "422": {
                        "description": "绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/case/delete/:id": {
            "get": {
                "description": "删除单一Case，一般用户只可以删除自己的，特殊权限者可以删除任何人的，注意：如果案件正在处理中，则无法删除",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "case"
                ],
                "summary": "通过 ID（调解案件ID，不是case_id）删除case",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "没有认证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/case/id/:id": {
            "get": {
                "description": "获取单一Case， 例子：9",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "case"
                ],
                "summary": "通过ID（主键）获取case",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "没有认证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/case/update/:id": {
            "post": {
                "description": "由申请人填写修改调解案件，申请人、管理员、部门人员可以修改，只可以修改案件信息，不可以修改案件状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "case"
                ],
                "summary": "修改调解案件",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "案件模型id，注意：不是案件号",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "提交表单",
                        "name": "case",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.CaseFirstSubmitForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "没有认证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "422": {
                        "description": "绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/category": {
            "get": {
                "description": "获取所有类型",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category",
                    "case"
                ],
                "summary": "获得所有类型",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/department/create": {
            "post": {
                "description": "创建单位，只有管理员可以使用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "department"
                ],
                "summary": "创建department",
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/department/delete/:id": {
            "get": {
                "description": "删除单一单位，只有管理员可以操作",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "department"
                ],
                "summary": "通过 ID 删除 department",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "没有认证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/department/id/:id": {
            "get": {
                "description": "获取指定单位的信息，所有人都可以使用",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "department"
                ],
                "summary": "获取指定单位的信息",
                "parameters": [
                    {
                        "type": "number",
                        "description": "表单id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/department/list": {
            "get": {
                "description": "获取所有相关单位信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "department"
                ],
                "summary": "获取所有相关单位信息",
                "parameters": [
                    {
                        "type": "number",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "页大小",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/labor/create": {
            "post": {
                "description": "劳动争议案件审判要素表新建",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "labor"
                ],
                "summary": "创建劳动争议案件审判要素表",
                "parameters": [
                    {
                        "description": "表单",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.LaborArbitrationForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "422": {
                        "description": "表单绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "500": {
                        "description": "表单绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/labor/delete/:id": {
            "get": {
                "description": "劳动争议案件审判要素表删除，非管理员只能删除自己的，如果有案件依赖则不可以删除",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "labor"
                ],
                "summary": "删除单个劳动争议案件审判要素表",
                "parameters": [
                    {
                        "type": "number",
                        "description": "表单id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/labor/id/:id": {
            "get": {
                "description": "劳动争议案件审判要素表获取，非管理员只能看自己的。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "labor"
                ],
                "summary": "获取指定劳动争议案件审判要素表列表",
                "parameters": [
                    {
                        "type": "number",
                        "description": "表单id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/labor/list": {
            "get": {
                "description": "劳动争议案件审判要素表列表，记住，只能看到自己的！！！",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "labor"
                ],
                "summary": "获取自己所有的劳动争议案件审判要素表",
                "parameters": [
                    {
                        "type": "number",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "页大小",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/labor/update/:id": {
            "post": {
                "description": "劳动争议案件审判要素表修改，只能修改未绑定到案件的表单，已绑定到案件的，不可修改，另外，每个人只能修改自己的表单，除了管理员，其他人不可以修改",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "labor"
                ],
                "summary": "修改劳动争议案件审判要素表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "表单id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "表单",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.LaborArbitrationForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "422": {
                        "description": "表单绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "500": {
                        "description": "表单绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/test/case/template": {
            "get": {
                "description": "获取申请调解案件的上传模板，测试用",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "case",
                    "test"
                ],
                "summary": "获取申请调解案件的上传模板",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "没有认证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/test/labor/template": {
            "post": {
                "description": "获取劳动争议表单模板",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test",
                    "labor"
                ],
                "summary": "获取劳动争议表单模板",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.CommonData"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/user/info": {
            "get": {
                "description": "获取用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.UserData"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/user/reset_password": {
            "post": {
                "description": "用户自行修改密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "原始密码",
                        "name": "old_password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "新密码，最小长度3 最大长度20",
                        "name": "new_password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "重新输入密码",
                        "name": "confirm_password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "422": {
                        "description": "表单绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "500": {
                        "description": "表单绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        },
        "/api/v1/user/update_info": {
            "post": {
                "description": "修改用户邮箱和密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "修改用户基础信息（邮箱和密码）",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.UserUpdateInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常业务处理",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "401": {
                        "description": "未验证",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "422": {
                        "description": "表单绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    },
                    "500": {
                        "description": "表单绑定失败",
                        "schema": {
                            "$ref": "#/definitions/vo.Common"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "jwtmodel.UserClaims": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "iss": {
                    "type": "string"
                },
                "realm": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "sub": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "models.Department": {
            "type": "object",
            "properties": {
                "contact": {
                    "description": "机构联系方式",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建日期，提交表单时不要上传该信息",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "删除日期 提交表单时不要上传该信息",
                    "type": "string"
                },
                "description": {
                    "description": "机构介绍",
                    "type": "string"
                },
                "id": {
                    "description": "模型ID，提交表单时不要上传该信息",
                    "type": "integer"
                },
                "name": {
                    "description": "机构、单位名称",
                    "type": "string"
                },
                "service": {
                    "description": "机构提供的服务",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新日期，提交表单时不要上传该信息",
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "description": "创建日期，提交表单时不要上传该信息",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "删除日期 提交表单时不要上传该信息",
                    "type": "string"
                },
                "department": {
                    "description": "工会等用户",
                    "type": "object",
                    "$ref": "#/definitions/models.Department"
                },
                "email": {
                    "type": "string"
                },
                "email_checked": {
                    "type": "boolean"
                },
                "id": {
                    "description": "模型ID，提交表单时不要上传该信息",
                    "type": "integer"
                },
                "last_login": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "phone_checked": {
                    "type": "boolean"
                },
                "updated_at": {
                    "description": "更新日期，提交表单时不要上传该信息",
                    "type": "string"
                },
                "user_profile": {
                    "type": "object",
                    "$ref": "#/definitions/models.UserProfile"
                },
                "user_type": {
                    "description": "约定使用UserProfile中的某些字段",
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserProfile": {
            "type": "object",
            "properties": {
                "applicant_address": {
                    "description": "地址",
                    "type": "string"
                },
                "applicant_birth": {
                    "description": "生日",
                    "type": "string"
                },
                "applicant_contact": {
                    "description": "联系方式",
                    "type": "string"
                },
                "applicant_id": {
                    "description": "身份证号",
                    "type": "string"
                },
                "applicant_name": {
                    "description": "Model\n姓名",
                    "type": "string"
                },
                "applicant_nationality": {
                    "description": "民族",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建日期，提交表单时不要上传该信息",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "删除日期 提交表单时不要上传该信息",
                    "type": "string"
                },
                "employer_address": {
                    "description": "地址",
                    "type": "string"
                },
                "employer_contact": {
                    "description": "联系方式",
                    "type": "string"
                },
                "employer_faren": {
                    "description": "法人",
                    "type": "string"
                },
                "employer_name": {
                    "description": "Model\n公司名",
                    "type": "string"
                },
                "employer_uscc": {
                    "description": "识别号",
                    "type": "string"
                },
                "id": {
                    "description": "模型ID，提交表单时不要上传该信息",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "更新日期，提交表单时不要上传该信息",
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "vo.Applicant": {
            "type": "object",
            "required": [
                "applicant_address",
                "applicant_birth",
                "applicant_contact",
                "applicant_id",
                "applicant_name",
                "applicant_nationality"
            ],
            "properties": {
                "applicant_address": {
                    "description": "地址",
                    "type": "string"
                },
                "applicant_birth": {
                    "description": "生日",
                    "type": "string"
                },
                "applicant_contact": {
                    "description": "联系方式",
                    "type": "string"
                },
                "applicant_id": {
                    "description": "身份证号",
                    "type": "string"
                },
                "applicant_name": {
                    "description": "姓名",
                    "type": "string"
                },
                "applicant_nationality": {
                    "description": "民族",
                    "type": "string"
                }
            }
        },
        "vo.CaseFirstSubmitForm": {
            "type": "object",
            "required": [
                "applicant",
                "content",
                "form_id",
                "respondent",
                "title"
            ],
            "properties": {
                "applicant": {
                    "description": "1.申请人",
                    "type": "object",
                    "$ref": "#/definitions/vo.Applicant"
                },
                "category_id": {
                    "description": "类型id",
                    "type": "integer"
                },
                "content": {
                    "description": "4.调解事项所依据的事实与理由",
                    "type": "string"
                },
                "form_id": {
                    "description": "5.劳动者填写的表单 id",
                    "type": "integer"
                },
                "materials": {
                    "description": "6. 证据材料",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.Material"
                    }
                },
                "respondent": {
                    "description": "2.被申请人",
                    "type": "object",
                    "$ref": "#/definitions/vo.Employer"
                },
                "title": {
                    "description": "3.调解事项",
                    "type": "string"
                }
            }
        },
        "vo.Common": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "unauthorized"
                },
                "status": {
                    "type": "integer",
                    "example": 401
                },
                "timestamp": {
                    "type": "string",
                    "example": "2048-05-06 12:34:56"
                }
            }
        },
        "vo.CommonData": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string",
                    "example": "unauthorized"
                },
                "status": {
                    "type": "integer",
                    "example": 401
                },
                "timestamp": {
                    "type": "string",
                    "example": "2048-05-06 12:34:56"
                }
            }
        },
        "vo.Employer": {
            "type": "object",
            "required": [
                "employer_address",
                "employer_contact",
                "employer_faren",
                "employer_name",
                "employer_uscc"
            ],
            "properties": {
                "employer_address": {
                    "description": "地址",
                    "type": "string"
                },
                "employer_contact": {
                    "description": "联系方式",
                    "type": "string"
                },
                "employer_faren": {
                    "description": "法人",
                    "type": "string"
                },
                "employer_name": {
                    "description": "公司名",
                    "type": "string"
                },
                "employer_uscc": {
                    "description": "识别号",
                    "type": "string"
                }
            }
        },
        "vo.LaborArbitrationForm": {
            "type": "object",
            "required": [
                "arbitration_time",
                "hire_date",
                "main",
                "parties_dispute_time",
                "payment_cycle",
                "payment_type",
                "wage"
            ],
            "properties": {
                "arbitration_time": {
                    "description": "28. 申请仲裁时间年月日",
                    "type": "string"
                },
                "before_sever_labor_relationship_avg_wage": {
                    "description": "20. 双方解除或终止劳动关系前12个月劳动者月平均工资额",
                    "type": "number",
                    "example": 1
                },
                "before_sever_labor_relationship_range": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "contract_wage": {
                    "description": "8. 劳动合同约定的月工资数、工资构成、工时制\n8.1 劳动合同约定的月工资数",
                    "type": "number"
                },
                "contract_wage_component": {
                    "description": "8.2 劳动合同约定的工资构成",
                    "type": "string"
                },
                "contract_wage_type": {
                    "description": "8.3 工时制",
                    "type": "integer"
                },
                "created_at": {
                    "description": "0.3 CreatedAt 新建时不填写",
                    "type": "string"
                },
                "disability_rating_time": {
                    "description": "15. 伤残等级鉴定时间及结果\n15.1 伤残等级鉴定时间",
                    "type": "string"
                },
                "disable_results": {
                    "description": "15.2 伤残等级鉴定结果",
                    "type": "integer"
                },
                "employer_time": {
                    "description": "16.2 用人单位",
                    "type": "number",
                    "example": 1
                },
                "hire_date": {
                    "description": "2. 入职时间",
                    "type": "string"
                },
                "hospitalization_time": {
                    "description": "14. 住院起止时间",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "0.1 ID, 新建时不填写",
                    "type": "integer"
                },
                "industrial_injury": {
                    "description": "13.2 是否经过工伤认定",
                    "type": "boolean"
                },
                "injury_time": {
                    "description": "13. 发生工伤时间、工伤认定情况\n13.1 发生工伤时间",
                    "type": "string"
                },
                "involve_group": {
                    "description": "29. 涉及群体性是□否□",
                    "type": "boolean"
                },
                "job_name": {
                    "description": "6. 劳动合同约定的工作岗位",
                    "type": "string"
                },
                "job_work_place": {
                    "description": "7. 劳动合同约定的工作地点",
                    "type": "string"
                },
                "labor_contract": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "labor_contract_completed": {
                    "description": "27. 已办理劳动合同解除手续",
                    "type": "boolean"
                },
                "labor_contract_not_signed": {
                    "description": "5. 未签书面劳动合同工作期间",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "labor_contract_signed": {
                    "description": "3.1 是否签订书面劳动合同",
                    "type": "boolean"
                },
                "labor_contract_signing_date": {
                    "description": "3.2 签订时间",
                    "type": "string"
                },
                "labor_contract_type": {
                    "description": "4.劳动合同起止时间",
                    "type": "integer"
                },
                "laborer_time": {
                    "description": "16. 停工留薪期限时间  //格式都不对\n16.1 劳动者",
                    "type": "number",
                    "example": 1
                },
                "last_payment": {
                    "description": "10. 最后一次支付工资时间",
                    "type": "string",
                    "example": "2010-01"
                },
                "main": {
                    "description": "1. 主体性质",
                    "type": "integer"
                },
                "no_overtime_avg_wage": {
                    "description": "23. 扣除加班工资后十二个月劳动者月平均工资数额",
                    "type": "number",
                    "example": 1
                },
                "no_overtime_avg_wage_range": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "normal_overtime": {
                    "description": "18. 加班时间",
                    "type": "number",
                    "example": 10
                },
                "not_take_days": {
                    "description": "未休",
                    "type": "integer"
                },
                "number": {
                    "description": "3.3 签订次数",
                    "type": "integer"
                },
                "other_information": {
                    "description": "30. 本表遗漏的其他项目",
                    "type": "string"
                },
                "overtime_bonus": {
                    "description": "11.2 欠发加班费奖金",
                    "type": "number"
                },
                "overtime_wage_base": {
                    "description": "19. 加班工资计算基数",
                    "type": "number",
                    "example": 2
                },
                "owner": {
                    "description": "0.2 Owner 新建时不填写",
                    "type": "integer"
                },
                "paid_annual_leave_not_leave_day": {
                    "description": "22. 未休带薪年休假天数",
                    "type": "boolean"
                },
                "parties_dispute_time": {
                    "description": "24.双方发生劳动争议时间",
                    "type": "string",
                    "example": "2020-01-02"
                },
                "payment_cycle": {
                    "description": "9.4 发放周期",
                    "type": "integer"
                },
                "payment_type": {
                    "description": "9.3 发放形式",
                    "type": "integer"
                },
                "real_rest": {
                    "description": "实休",
                    "type": "integer"
                },
                "sever_labor_relationship_date": {
                    "description": "26.解除或终止劳动关系时间年月日",
                    "type": "string",
                    "example": "2020-01-02"
                },
                "sever_labor_relationship_employer": {
                    "description": "25. 双方解除或终止劳动关系的原因",
                    "type": "boolean"
                },
                "sever_labor_relationship_employer_reason": {
                    "type": "string"
                },
                "sever_labor_relationship_labor": {
                    "type": "boolean"
                },
                "sever_labor_relationship_labor_reason": {
                    "type": "string"
                },
                "should_rest": {
                    "description": "应休",
                    "type": "integer"
                },
                "social_insurance": {
                    "description": "12.办理社会保险及险种\n12.1 是否进行社会保险",
                    "type": "boolean"
                },
                "social_insurance_payment_time": {
                    "description": "12.3 社会保险缴险时间",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "social_insurance_type": {
                    "description": "12.2 社会保险险种",
                    "type": "integer"
                },
                "statutory_holidays": {
                    "description": "法定节假日加班小时",
                    "type": "number",
                    "example": 10
                },
                "statutory_rest": {
                    "description": "法定休息日加班小时",
                    "type": "number",
                    "example": 10
                },
                "unpaid_wages": {
                    "description": "11. 欠发工资及加班费数额\n11.1 欠发工资数",
                    "type": "number"
                },
                "updated_at": {
                    "description": "0.4 UpdatedAt 新建时不填写",
                    "type": "string"
                },
                "wage": {
                    "description": "9. 实发月工资数及工资构成、发放形式、发放周期\n9.1 月工资数",
                    "type": "number"
                },
                "wage_component": {
                    "description": "9.2 工资构成",
                    "type": "string"
                },
                "work_related_treatment_gsylbz": {
                    "description": "17.9. 一次性工伤医疗补助金",
                    "type": "number"
                },
                "work_related_treatment_hsbz": {
                    "description": "17.3 住院期间伙食补助",
                    "type": "number"
                },
                "work_related_treatment_jt": {
                    "description": "17.4 交通费",
                    "type": "number"
                },
                "work_related_treatment_jzaz": {
                    "description": "17.2 假肢安装费",
                    "type": "number"
                },
                "work_related_treatment_other": {
                    "description": "17.11. 其他",
                    "type": "number"
                },
                "work_related_treatment_ph": {
                    "description": "17.5 陪护费",
                    "type": "number"
                },
                "work_related_treatment_scbz": {
                    "description": "17.8 一次性伤残补助金",
                    "type": "number"
                },
                "work_related_treatment_scjt": {
                    "description": "17.7 伤残津贴",
                    "type": "number"
                },
                "work_related_treatment_scjybz": {
                    "description": "17.10. 一次性伤残就业补助金",
                    "type": "number"
                },
                "work_related_treatment_shhl": {
                    "description": "17.6 生活护理费",
                    "type": "number"
                },
                "work_related_treatment_ylf": {
                    "description": "17.需支付的工伤待遇项目及数额\n17.1 医疗费",
                    "type": "number"
                },
                "work_year": {
                    "description": "21. 劳动者在本单位工作年限",
                    "type": "integer"
                }
            }
        },
        "vo.LoginResult": {
            "type": "object",
            "properties": {
                "expire": {
                    "type": "string"
                },
                "message": {
                    "type": "string",
                    "example": "unauthorized"
                },
                "refresh_url": {
                    "type": "string",
                    "example": "/api/auth/refreshToken"
                },
                "status": {
                    "type": "integer",
                    "example": 401
                },
                "timestamp": {
                    "type": "string",
                    "example": "2048-05-06 12:34:56"
                },
                "token": {
                    "type": "string",
                    "example": "asdsadasdasdasd"
                }
            }
        },
        "vo.Material": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "材料介绍",
                    "type": "string"
                },
                "path": {
                    "description": "材料资源path",
                    "type": "string"
                }
            }
        },
        "vo.UserData": {
            "type": "object",
            "properties": {
                "claims": {
                    "type": "object",
                    "$ref": "#/definitions/jwtmodel.UserClaims"
                },
                "message": {
                    "type": "string",
                    "example": "unauthorized"
                },
                "profile": {
                    "type": "object",
                    "$ref": "#/definitions/models.UserProfile"
                },
                "status": {
                    "type": "integer",
                    "example": 401
                },
                "timestamp": {
                    "type": "string",
                    "example": "2048-05-06 12:34:56"
                },
                "user": {
                    "type": "object",
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "vo.UserRegisterEmployerForm": {
            "type": "object",
            "required": [
                "confirm_password",
                "employer",
                "password",
                "phone"
            ],
            "properties": {
                "confirm_password": {
                    "type": "string"
                },
                "employer": {
                    "type": "object",
                    "$ref": "#/definitions/vo.Employer"
                },
                "password": {
                    "description": "Username        string   ` + "`" + `json:\"username\" form:\"username\" binding:\"required,min=3,max=20\"` + "`" + `",
                    "type": "string"
                },
                "phone": {
                    "type": "string",
                    "example": "13800138000"
                }
            }
        },
        "vo.UserRegisterLaborForm": {
            "type": "object",
            "required": [
                "applicant",
                "confirm_password",
                "password",
                "phone"
            ],
            "properties": {
                "applicant": {
                    "type": "object",
                    "$ref": "#/definitions/vo.Applicant"
                },
                "confirm_password": {
                    "type": "string"
                },
                "password": {
                    "description": "Username        string    ` + "`" + `json:\"username\" form:\"username\" binding:\"required,min=3,max=20\"` + "`" + `",
                    "type": "string"
                },
                "phone": {
                    "type": "string",
                    "example": "13800138000"
                }
            }
        },
        "vo.UserUpdateInfo": {
            "type": "object",
            "required": [
                "email",
                "phone"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "hafrans@163.com"
                },
                "phone": {
                    "type": "string",
                    "example": "13800138000"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.2",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "岚山区劳动争议调解区块链平台",
	Description: "岚山区劳动争议调解区块链平台，后台采用golang开发，使用gin + gorm + gorbac + jwt开发",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
